export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  USER_BANNED: 'USER_BANNED',
  FORBIDDEN_PLATFORM_ROLE: 'FORBIDDEN_PLATFORM_ROLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  EXPERT_NOT_FOUND: 'EXPERT_NOT_FOUND',
  EXPERT_MEMBER_ALREADY_EXISTS: 'EXPERT_MEMBER_ALREADY_EXISTS',
  EXPERT_MEMBER_NOT_FOUND: 'EXPERT_MEMBER_NOT_FOUND',
  INVALID_EXPERT_MEMBER_ROLE: 'INVALID_EXPERT_MEMBER_ROLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
